Fix monitor regression tests.
Also attempt to test the upgrade from 1.0 to 1.1, which currently fails
because of a strange syntax error:

    ALTER EXTENSION pgautofailover UPDATE TO '1.1';
    ERROR:  syntax error at or near "ALTER"